### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by CharlottesWebMD** [JonathanWolfe/BetterMangaReader#4]
I'm really not sure what happened when you updated this extension, but it has been an absolute nightmare to deal with. Not only was all of my data completely wiped out, but there is no longer any way to import data even if I had a backup file. I have manually gone in and started tracking around 150 or so manga's that I keep up with twice now. I have opened Google Chrome to find out that once again almost all of the Manga that I manually had to start tracking has been wiped out. It only saves about 30 or so and the one's it chooses to save are different every time. I really loved using this extension because it was clearly the best option, but no so anymore. I really hope these are bugs that just need to be fixed because I can't keep wasting time trying to track Manga not knowing if it's going to save or not.

**Comment by JonathanWolfe** [comment]
Sorry you've been having issues.

Has this all been yesterday? Or over the past few days. I did have a couple releases between `0.5.0` and now that could error out during certain scenarios.

Do make sure you have `0.5.9` which is that latest version out.

If those bugs are happening right now I'll send you some commands to run to get me your data to test and check.

**Comment by CharlottesWebMD** [comment]
I uninstalled and reinstalled the new update when this starting happening. The link redirects me to the extension in the Google Chrome store and shows that the current update is installed.

**Comment by JonathanWolfe** [comment]
The store version can only support ~90 manga at the moment but the next one will have capacity for 1200+.  (Chrome storage has different quotas depending on how you store the data)

If you see the problem occur, open the extensions page and check the developer check box. Then click the link under BMR that says inspect background page and see if there are any errors listed in there.

**Comment by CharlottesWebMD** [comment]
I will try that, thank you for your help. My issue probably has to do with the size capacity since I had several hundred saved in the previous version.

**Comment by JonathanWolfe** [comment]
That's what I think.

I expect the next update to go out today or tomorrow. Whenever I finish doing some stress tests of the new storage layout.

**Comment by JonathanWolfe** [comment]
Just wanted to let you know that I just released `0.5.11` which should solve your storage space issues. It should be distributed by the Chrome Store within an hour.
