### ISSUE TITLE
Manga Town Missing Images

### ISSUE THREAD

**Issue by koolio0623** [JonathanWolfe/BetterMangaReader#5]
When I'm using this addon for Mangatown I'm frequently refreshing the page because of unloaded pages. I was wondering if this is a common problem and if so whether or not there is a fix.
Apologies in advance I don't know your preferred platform or format for reports like these.

**Comment by JonathanWolfe** [comment]
That's an issue with MangaTown and their cache system (also MangaHere since they're run and made by the same people). I have the same problem as you. I'm considering adding failed image retries, but I haven't thought of the best way to do it yet.

**Comment by koolio0623** [comment]
Ah. I see. Thank you for the clarification :)

**Comment by JonathanWolfe** [comment]
You'll notice it happens more on less popular manga since there's a lower chance of someone else having recently also viewed that same manga page and warm the cache.

I'll ping this issue if/when I release an update with failed image retries.

Thanks for using BMR!
